package go_referrer_type

// Default Result Types
const TYPE_REFERRER_ORGANIC_SEARCH_ETC = 100; // organic etc
const TYPE_REFERRER_ORGANIC_SEARCH_YAHOO = 101; // organic yahoo
const TYPE_REFERRER_ORGANIC_SEARCH_GOOGLE = 102; // organic google
const TYPE_REFERRER_LINK_OUTER = 201; // direct link outer
const TYPE_REFERRER_LINK_INNER = 202; // direct link inner
const TYPE_REFERRER_SOCIAL_ETC = 300; // social outer
const TYPE_REFERRER_SOCIAL_TWITTER = 301; // social titter
const TYPE_REFERRER_SOCIAL_FACEBOOK = 302; // social facebook
const TYPE_REFERRER_SOCIAL_INSTAGRAM = 303; // social instagram
const TYPE_REFERRER_AD_YAHOO_CPC = 401; // adWords yahoo cpc
const TYPE_REFERRER_AD_GOOGLE_CPC = 402; // adWords google cpc
const TYPE_REFERRER_AD_YAHOO_DISPLAY = 403; // adWords yahoo display
const TYPE_REFERRER_AD_GOOGLE_DISPLAY = 404; // adWords google display
const TYPE_REFERRER_AD_YAHOO_REMARKETING = 405; // adWords yahoo remarketing
const TYPE_REFERRER_AD_GOOGLE_REMARKETING = 406; // adWords google remarketing
const TYPE_REFERRER_NONE = 999; // referrer none

type ResultType struct {
	TYPE_REFERRER_ORGANIC_SEARCH_ETC    int
	TYPE_REFERRER_ORGANIC_SEARCH_YAHOO  int
	TYPE_REFERRER_ORGANIC_SEARCH_GOOGLE int
	TYPE_REFERRER_LINK_OUTER            int
	TYPE_REFERRER_LINK_INNER            int
	TYPE_REFERRER_SOCIAL_ETC            int
	TYPE_REFERRER_SOCIAL_TWITTER        int
	TYPE_REFERRER_SOCIAL_FACEBOOK       int
	TYPE_REFERRER_SOCIAL_INSTAGRAM      int
	TYPE_REFERRER_AD_YAHOO_CPC          int
	TYPE_REFERRER_AD_GOOGLE_CPC         int
	TYPE_REFERRER_AD_YAHOO_DISPLAY      int
	TYPE_REFERRER_AD_GOOGLE_DISPLAY     int
	TYPE_REFERRER_AD_YAHOO_REMARKETING  int
	TYPE_REFERRER_AD_GOOGLE_REMARKETING int
	TYPE_REFERRER_NONE                  int
}

func CreateResultType() ResultType {
	return ResultType{
		TYPE_REFERRER_ORGANIC_SEARCH_ETC:TYPE_REFERRER_ORGANIC_SEARCH_ETC,
		TYPE_REFERRER_ORGANIC_SEARCH_YAHOO:TYPE_REFERRER_ORGANIC_SEARCH_YAHOO,
		TYPE_REFERRER_ORGANIC_SEARCH_GOOGLE:TYPE_REFERRER_ORGANIC_SEARCH_GOOGLE,
		TYPE_REFERRER_LINK_OUTER:TYPE_REFERRER_LINK_OUTER,
		TYPE_REFERRER_LINK_INNER:TYPE_REFERRER_LINK_INNER,
		TYPE_REFERRER_SOCIAL_ETC:TYPE_REFERRER_SOCIAL_ETC,
		TYPE_REFERRER_SOCIAL_TWITTER:TYPE_REFERRER_SOCIAL_TWITTER,
		TYPE_REFERRER_SOCIAL_FACEBOOK:TYPE_REFERRER_SOCIAL_FACEBOOK,
		TYPE_REFERRER_SOCIAL_INSTAGRAM:TYPE_REFERRER_SOCIAL_INSTAGRAM,
		TYPE_REFERRER_AD_YAHOO_CPC:TYPE_REFERRER_AD_YAHOO_CPC,
		TYPE_REFERRER_AD_GOOGLE_CPC:TYPE_REFERRER_AD_GOOGLE_CPC,
		TYPE_REFERRER_AD_YAHOO_DISPLAY:TYPE_REFERRER_AD_YAHOO_DISPLAY,
		TYPE_REFERRER_AD_GOOGLE_DISPLAY:TYPE_REFERRER_AD_GOOGLE_DISPLAY,
		TYPE_REFERRER_AD_YAHOO_REMARKETING:TYPE_REFERRER_AD_YAHOO_REMARKETING,
		TYPE_REFERRER_AD_GOOGLE_REMARKETING:TYPE_REFERRER_AD_GOOGLE_REMARKETING,
		TYPE_REFERRER_NONE:TYPE_REFERRER_NONE,
	}
}
